### ISSUE TITLE
Build errors if "src" directory in project path

### ISSUE THREAD

**Issue by luckydye** [spacedriveapp/spacedrive#1185]
### Describe the bug

Running `pnpm desktop dev` will error if the project was cloned into a path including a "src" directory.

### Reproduction

1. Create a directory called "src" somewhere on your drive.
2. Clone the spacedrive repo into that directory.
3. Follow the setup in the Contribution guide.
4. run `pnpm desktop dev`

### Platform and versions

```Shell
OSX 13.5
pnpm 8.6.11
cargo 1.71.0 (cfd3bbd8f 2023-06-08)
rustc 1.71.0 (8ede3aae2 2023-07-12)
```

### Stack trace

``` 
ERROR  2:42:09 PM [vite] Internal server error: The "path" argument must be of type string. Received undefined                                        14:42:09
  Plugin: vite:import-analysis
  File: /Users/tihav/src/github/spacedrive/apps/desktop/src/index.tsx
      at new NodeError (node:internal/errors:405:5)
      at validateString (node:internal/validators:162:11)
      at Object.extname (node:path:1385:5)
      at Context.customResolver (/Users/tihav/src/github/spacedrive/apps/desktop/vite.config.ts:83:57)
      at async Object.resolveId (file:///Users/tihav/src/github/spacedrive/apps/desktop/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42847:32)
      at async TransformContext.resolve (file:///Users/tihav/src/github/spacedrive/apps/desktop/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42575:23)
      at async normalizeUrl (file:///Users/tihav/src/github/spacedrive/apps/desktop/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:40500:34)
      at async file:///Users/tihav/src/github/spacedrive/apps/desktop/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:40651:47
      at async Promise.all (index 2)
      at async TransformContext.transform (file:///Users/tihav/src/github/spacedrive/apps/desktop/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:40577:13)
      at async Object.transform (file:///Users/tihav/src/github/spacedrive/apps/desktop/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42919:30)
      at async loadAndTransform (file:///Users/tihav/src/github/spacedrive/apps/desktop/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:53385:29)
```

### Additional context

The custom resolver in vite splits the importer path by "src", wich will cause problems when people clone the repo inside a "src" directory.

**Comment by Brendonovich** [comment]
@luckydye would you mind PRing the change on your fork?
