### ISSUE TITLE
Error running pnpm i on macOS (Node.js v19)

### ISSUE THREAD

**Issue by JSSRDRG** [spacedriveapp/spacedrive#1412]
### Describe the bug

postinstall from `pnpm i` fails on macOS (Intel)

```sh
spacedrive % pnpm i 
Scope: all 13 workspace projects
Lockfile is up to date, resolution step is skipped
Packages: +3052
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 0, reused 2514, downloaded 0, added 3052, done
. postinstall$ pnpm exec node scripts/post-install.mjs
│ Downloading pdfium...
│ Downloading FFMPeg...
│ Dowloading patched tauri CLI...
│ Downloading protoc...
│ Generating cargo config...
│ Setup Frameworks & Sign libraries...
│ node:internal/errors:490
│     ErrorCaptureStackTrace(err);
│     ^
│ TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
│     at new NodeError (node:internal/errors:399:5)
│     at validateString (node:internal/validators:163:11)
│     at Module.join (node:path:1176:7)
│     at file:///Users/jssrdrg/Documents/GitHub/spacedrive/scripts/post-install.mjs:170:23
│     at Array.map (<anonymous>)
│     at file:///Users/jssrdrg/Documents/GitHub/spacedrive/scripts/post-install.mjs:169:5 {
│   code: 'ERR_INVALID_ARG_TYPE'
│ }
│ Node.js v19.7.0
└─ Failed in 12.1s at /Users/jssrdrg/Documents/GitHub/spacedrive
 ELIFECYCLE  Command failed with exit code 1.
```

### Reproduction

1. Git clone repo
2. Checkout main
3. Run setup script
4. Run `pnpm i`

### Expected behavior

Finish pnpm install without errors

### Platform and versions

```Shell
pnpm 8.8.0
cargo 1.70.0 (ec8a8a0ca 2023-04-25)
rustc 1.70.0 (90c541806 2023-05-31)

macOS 14.0 (23A344)
```

**Comment by HeavenVolkoff** [comment]
We don't support node 19, only the last LTS and latest version, right now node >=v18.17 and >=v20.10. I will update the engine definition in the package.json to reflect our current supported node versions

**Comment by JSSRDRG** [comment]
Gotcha, tested both LTS and Latest, pnpm i worked again
