### ISSUE TITLE
[ENG-1253] P2P system crashes app if IPv4/IPv6 stack is not available

### ISSUE THREAD

**Issue by nick-s-b** [spacedriveapp/spacedrive#1503]
### Describe the bug

Hi all,
I installed `spacedrive` and it crashes immediately after the start. I've also tried the AppImage and it behaves the same. I have no idea what the cause could be but "address" and "protocol" might be network related. If so, could it be because I don't have IPv6? I only have IPv4 running.

Thanks for looking into this.

````
$ ./Spacedrive-linux-x86_64.AppImage
2023-10-11T15:37:56.391900Z  INFO sd_core: Starting core with data directory '/home/nsb/.local/share/spacedrive'
2023-10-11T15:37:56.439029Z ERROR sd_core: panicked at /home/runner/work/spacedrive/spacedrive/crates/p2p/src/manager.rs:80:10:
called `Result::unwrap()` on an `Err` value: Other(Custom { kind: Other, error: Io(Os { code: 97, kind: Uncategorized, message: "Address family not supported by protocol" }) }) panic.file="/home/runner/work/spacedrive/spacedrive/crates/p2p/src/manager.rs:80" panic.column=10
fatal runtime error: failed to initiate panic, error 3
[1]    769093 IOT instruction (core dumped)  ./Spacedrive-linux-x86_64.AppImage

````

### Reproduction

1. Run it.

### Platform and versions

```Shell
`
$ pnpm --version && cargo --version && rustc --version
8.9.0
cargo 1.73.0
rustc 1.73.0 (cc66ad468 2023-10-03) (Arch Linux rust 1:1.73.0-1)


$ uname -a
Linux aaa 6.5.6-arch2-1 #1 SMP PREEMPT_DYNAMIC Sat, 07 Oct 2023 08:14:55 +0000 x86_64 GNU/Linux
````
```


### Stack trace

```Shell
`
$ RUST_BACKTRACE=full spacedrive
2023-10-11T15:30:35.280063Z  INFO sd_core: Starting core with data directory '/home/aaa/.local/share/spacedrive'
2023-10-11T15:30:35.282062Z ERROR sd_core: panicked at 'called `Result::unwrap()` on an `Err` value: Other(Custom { kind: Other, error: Io(Os { code: 97, kind: Uncategorized, message: "Address family not supported by protocol" }) })', /home/nim/code/spacedrive/crates/p2p/src/manager.rs:82:10
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Other(Custom { kind: Other, error: Io(Os { code: 97, kind: Uncategorized, message: "Address family not supported by protocol" }) })', /home/nim/code/spacedrive/crates/p2p/src/manager.rs:82:10
stack backtrace:
   0:     0x557ea198e47a - <unknown>
   1:     0x557ea19bc88f - <unknown>
   2:     0x557ea1989465 - <unknown>
   3:     0x557ea198e245 - <unknown>
   4:     0x557ea198fefe - <unknown>
   5:     0x557ea198fca5 - <unknown>
   6:     0x557ea0090981 - <unknown>
   7:     0x557ea19905e4 - <unknown>
   8:     0x557ea1990359 - <unknown>
   9:     0x557ea198e8e6 - <unknown>
  10:     0x557ea19900b2 - <unknown>
  11:     0x557e9fb37793 - <unknown>
  12:     0x557e9fb37c43 - <unknown>
  13:     0x557e9ff0fbf1 - <unknown>
  14:     0x557e9ff13e4f - <unknown>
  15:     0x557e9ff2925d - <unknown>
  16:     0x557e9ff02c12 - <unknown>
  17:     0x557e9ff05064 - <unknown>
  18:     0x557e9fcad30b - <unknown>
  19:     0x557e9fd7be4f - <unknown>
  20:     0x557e9fc6ee26 - <unknown>
  21:     0x557e9fd7e508 - <unknown>
  22:     0x557ea1981a0e - <unknown>
  23:     0x557e9fd7bf25 - <unknown>
  24:     0x7fb5f2c45cd0 - <unknown>
  25:     0x7fb5f2c45d8a - __libc_start_main
  26:     0x557e9fb37fb5 - <unknown>
  27:                0x0 - <unknown>
2023-10-11T15:30:35.282624Z  INFO sd_core::location::manager: Stopping location manager
````
```


### Additional context

_No response_

**Comment by HeavenVolkoff** [comment]
You are correct about the missing ipv6 being the cause of the crash. Our p2p system is failing to initialize due to there being no available ipv6 address, and due to missing a proper error handling it is bringing the whole app down, I will fix it. Thanks for the report

**Comment by oscartbeaumont** [comment]
I can take this one @HeavenVolkoff
