### ISSUE TITLE
Adding a location on windows causes a thread to panic

### ISSUE THREAD

**Issue by KAJdev** [spacedriveapp/spacedrive#246]
### Describe the bug

Selecting any kind of location on windows causes a full panic.

### Reproduction

1. Compile Spacedrive for windows ;)
2. Click "Add Location" button in sidebar
3. Select any location and click "Open"

### Expected behavior

The location is added in the side bar.

### Platform and versions

```Shell
Windows 11
pnpm version: 7.2.1
cargo 1.61.0 (a028ae42f 2022-04-29)
rustc 1.61.0 (fe5b13d68 2022-05-18)
```

### Stack trace

```Shell
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError(())', C:\Users\KAJ7\Documents\GitHub\spacedrive\core\src\lib.rs:63:20
stack backtrace:
   0:     0x7ff649347f6f - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff649347f6f - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff649347f6f - std::sys_common::backtrace::_print_fmt
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:66
   3:     0x7ff649347f6f - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:45
   4:     0x7ff64936a6ca - core::fmt::write
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\fmt\mod.rs:1194
   5:     0x7ff64933ef69 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\io\mod.rs:1655
   6:     0x7ff64934a96b - std::sys_common::backtrace::_print
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:48
   7:     0x7ff64934a96b - std::sys_common::backtrace::print
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:35
   8:     0x7ff64934a96b - std::panicking::default_hook::closure$1
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:295
   9:     0x7ff64934a55e - std::panicking::default_hook
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:314
  10:     0x7ff64934af61 - std::panicking::rust_panic_with_hook
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:698
  11:     0x7ff64934ae1d - std::panicking::begin_panic_handler::closure$0
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:588
  12:     0x7ff649348877 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:138
  13:     0x7ff64934aaf9 - std::panicking::begin_panic_handler
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:584
  14:     0x7ff64956b475 - core::panicking::panic_fmt
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\panicking.rs:143
  15:     0x7ff64956b583 - core::result::unwrap_failed
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\result.rs:1785
  16:     0x7ff6464ef5bb - enum$<core::result::Result<enum$<core::result::Result<enum$<sdcore::CoreResponse>,enum$<sdcore::CoreError> > >,tokio::sync::oneshot::error::RecvError>, 0, 1, Ok>::unwrap<enum$<core::result::Result<enum$<sdcore::CoreResponse>,enum$<sdcore::CoreError> > >,t
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\result.rs:1078
  17:     0x7ff6462b2cac - sdcore::impl$0::command::async_fn$0
                               at C:\Users\KAJ7\Documents\GitHub\spacedrive\core\src\lib.rs:63
  18:     0x7ff6464c3617 - core::future::from_generator::impl$1::poll<enum$<sdcore::impl$0::command::async_fn_env$0> >
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\future\mod.rs:91
  19:     0x7ff646185dab - spacedrive::client_command_transport::async_fn$0
                               at C:\Users\KAJ7\Documents\GitHub\spacedrive\apps\desktop\src-tauri\src\main.rs:31
  20:     0x7ff6464ca477 - core::future::from_generator::impl$1::poll<enum$<spacedrive::client_command_transport::async_fn_env$0> >
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\future\mod.rs:91
  21:     0x7ff6464bdc7b - futures_core::future::impl$2::try_poll<core::future::from_generator::GenFuture<enum$<spacedrive::client_command_transport::async_fn_env$0> >,enum$<sdcore::CoreResponse>,alloc::string::String>
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-core-0.3.21\src\future.rs:82
  22:     0x7ff646507748 - futures_util::future::try_future::into_future::impl$2::poll<core::future::from_generator::GenFuture<enum$<spacedrive::client_command_transport::async_fn_env$0> > >
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.21\src\future\try_future\into_future.rs:34
  23:     0x7ff64625f52b - futures_util::future::future::map::impl$2::poll<futures_util::future::try_future::into_future::IntoFuture<core::future::from_generator::GenFuture<enum$<spacedrive::client_command_transport::async_fn_env$0> > >,futures_util::fns::MapErrFn<futures_util::fns
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.21\src\future\future\map.rs:55
  24:     0x7ff64609ffb8 - futures_util::future::future::impl$15::poll<futures_util::future::try_future::into_future::IntoFuture<core::future::from_generator::GenFuture<enum$<spacedrive::client_command_transport::async_fn_env$0> > >,futures_util::fns::MapErrFn<futures_util::fns::In
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.21\src\lib.rs:91
  25:     0x7ff646462fd8 - futures_util::future::try_future::impl$61::poll<core::future::from_generator::GenFuture<enum$<spacedrive::client_command_transport::async_fn_env$0> >,futures_util::fns::IntoFn<tauri::hooks::InvokeError> >
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.21\src\lib.rs:91
  26:     0x7ff646463038 - futures_util::future::try_future::impl$36::poll<core::future::from_generator::GenFuture<enum$<spacedrive::client_command_transport::async_fn_env$0> >,tauri::hooks::InvokeError>
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.21\src\lib.rs:91
  27:     0x7ff64625ee6b - futures_util::future::future::map::impl$2::poll<futures_util::future::try_future::ErrInto<core::future::from_generator::GenFuture<enum$<spacedrive::client_command_transport::async_fn_env$0> >,tauri::hooks::InvokeError>,tauri::command::private::impl$7::fut
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.21\src\future\future\map.rs:55
  28:     0x7ff64609fe98 - futures_util::future::future::impl$15::poll<futures_util::future::try_future::ErrInto<core::future::from_generator::GenFuture<enum$<spacedrive::client_command_transport::async_fn_env$0> >,tauri::hooks::InvokeError>,tauri::command::private::impl$7::future:
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.21\src\lib.rs:91
  29:     0x7ff64618b4ac - spacedrive::main::async_block$0::closure$4::async_block$1
                               at C:\Users\KAJ7\Documents\GitHub\spacedrive\apps\desktop\src-tauri\src\main.rs:26
  30:     0x7ff6464ca697 - core::future::from_generator::impl$1::poll<enum$<spacedrive::main::async_block$0::closure$4::async_block_env$1> >
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\future\mod.rs:91
  31:     0x7ff6462e0e74 - tauri::hooks::impl$7::respond_async_serialized::async_block$0<tauri_runtime_wry::Wry<enum$<tauri::EventLoopMessage> >,core::future::from_generator::GenFuture<enum$<spacedrive::main::async_block$0::closure$4::async_block_env$1> > >
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-1.0.0-rc.14\src\hooks.rs:196
  32:     0x7ff6464c88f9 - core::future::from_generator::impl$1::poll<enum$<tauri::hooks::impl$7::respond_async_serialized::async_block_env$0<tauri_runtime_wry::Wry<enum$<tauri::EventLoopMessage> >,core::future::from_generator::GenFuture<enum$<spacedrive::main::async_block$0::closu
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\future\mod.rs:91
  33:     0x7ff646331ff0 - tokio::runtime::task::core::impl$3::poll::closure$0<core::future::from_generator::GenFuture<enum$<tauri::hooks::impl$7::respond_async_serialized::async_block_env$0<tauri_runtime_wry::Wry<enum$<tauri::EventLoopMessage> >,core::future::from_generator::GenFu
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\runtime\task\core.rs:165
  34:     0x7ff64640dea2 - tokio::loom::std::unsafe_cell::UnsafeCell<enum$<tokio::runtime::task::core::Stage<core::future::from_generator::GenFuture<enum$<tauri::hooks::impl$7::respond_async_serialized::async_block_env$0<tauri_runtime_wry::Wry<enum$<tauri::EventLoopMessage> >,core:
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\loom\std\unsafe_cell.rs:14
  35:     0x7ff64633133f - tokio::runtime::task::core::CoreStage<core::future::from_generator::GenFuture<enum$<tauri::hooks::impl$7::respond_async_serialized::async_block_env$0<tauri_runtime_wry::Wry<enum$<tauri::EventLoopMessage> >,core::future::from_generator::GenFuture<enum$<spa
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\runtime\task\core.rs:155
  36:     0x7ff64653b92a - tokio::runtime::task::harness::poll_future::closure$0<core::future::from_generator::GenFuture<enum$<tauri::hooks::impl$7::respond_async_serialized::async_block_env$0<tauri_runtime_wry::Wry<enum$<tauri::EventLoopMessage> >,core::future::from_generator::Gen
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\runtime\task\harness.rs:470
  37:     0x7ff64638c973 - core::panic::unwind_safe::impl$23::call_once<enum$<core::task::poll::Poll<tuple$<> > >,tokio::runtime::task::harness::poll_future::closure_env$0<core::future::from_generator::GenFuture<enum$<tauri::hooks::impl$7::respond_async_serialized::async_block_env$
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\panic\unwind_safe.rs:271
  38:     0x7ff6460b8360 - std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<core::future::from_generator::GenFuture<enum$<tauri::hooks::impl$7::respond_async_serialized::async_block_env$0<tauri_runtime
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\std\src\panicking.rs:492
  39:     0x7ff6460c5813 - std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::impl$1::complete::closure_env$0<core::future::from_generator::GenFuture<enum$<tauri::hooks::impl$7::respond_async::async_block_env$0<tauri_runtime_wry:
  40:     0x7ff6460b0606 - std::panicking::try<enum$<core::task::poll::Poll<tuple$<> > >,core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<core::future::from_generator::GenFuture<enum$<tauri::hooks::impl$7::respond_async_serialized
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\std\src\panicking.rs:456
  41:     0x7ff6463796ab - std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<core::future::from_generator::GenFuture<enum$<tauri::hooks::impl$7::respond_async_serialized::async_block_env$0<tauri_runtime_wry
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\std\src\panic.rs:137
  42:     0x7ff6465371d8 - tokio::runtime::task::harness::poll_future<core::future::from_generator::GenFuture<enum$<tauri::hooks::impl$7::respond_async_serialized::async_block_env$0<tauri_runtime_wry::Wry<enum$<tauri::EventLoopMessage> >,core::future::from_generator::GenFuture<enum
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\runtime\task\harness.rs:458
  43:     0x7ff64653fb66 - tokio::runtime::task::harness::Harness<core::future::from_generator::GenFuture<enum$<tauri::hooks::impl$7::respond_async_serialized::async_block_env$0<tauri_runtime_wry::Wry<enum$<tauri::EventLoopMessage> >,core::future::from_generator::GenFuture<enum$<sp
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\runtime\task\harness.rs:104
  44:     0x7ff64655a263 - tokio::runtime::task::harness::Harness<core::future::from_generator::GenFuture<enum$<tauri::hooks::impl$7::respond_async_serialized::async_block_env$0<tauri_runtime_wry::Wry<enum$<tauri::EventLoopMessage> >,core::future::from_generator::GenFuture<enum$<sp
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\runtime\task\harness.rs:57
  45:     0x7ff6460ca152 - tokio::runtime::task::raw::poll<core::future::from_generator::GenFuture<enum$<tauri::hooks::impl$7::respond_async_serialized::async_block_env$0<tauri_runtime_wry::Wry<enum$<tauri::EventLoopMessage> >,core::future::from_generator::GenFuture<enum$<spacedriv
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\runtime\task\raw.rs:144
  46:     0x7ff6492a0150 - tokio::runtime::task::raw::RawTask::poll
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\runtime\task\raw.rs:84
  47:     0x7ff64923d432 - tokio::runtime::task::LocalNotified<alloc::sync::Arc<tokio::runtime::thread_pool::worker::Shared> >::run<alloc::sync::Arc<tokio::runtime::thread_pool::worker::Shared> >
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\runtime\task\mod.rs:376
  48:     0x7ff64928b95d - tokio::runtime::thread_pool::worker::impl$1::run_task::closure$0
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\runtime\thread_pool\worker.rs:431
  49:     0x7ff6492738c9 - tokio::coop::with_budget::closure$0<enum$<core::result::Result<alloc::boxed::Box<tokio::runtime::thread_pool::worker::Core,alloc::alloc::Global>,tuple$<> >, 1, 18446744073709551615, Ok>,tokio::runtime::thread_pool::worker::impl$1::run_task::closure_env$0>
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\coop.rs:102
  50:     0x7ff6492850ad - std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget> >::try_with<core::cell::Cell<tokio::coop::Budget>,tokio::coop::with_budget::closure_env$0<enum$<core::result::Result<alloc::boxed::Box<tokio::runtime::thread_pool::worker::Core,alloc::allo
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\std\src\thread\local.rs:442
  51:     0x7ff64928354d - std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget> >::with<core::cell::Cell<tokio::coop::Budget>,tokio::coop::with_budget::closure_env$0<enum$<core::result::Result<alloc::boxed::Box<tokio::runtime::thread_pool::worker::Core,alloc::alloc::G
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\std\src\thread\local.rs:418
  52:     0x7ff64928b7af - tokio::coop::with_budget
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\coop.rs:95
  53:     0x7ff64928b7af - tokio::coop::budget
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\coop.rs:72
  54:     0x7ff64928b7af - tokio::runtime::thread_pool::worker::Context::run_task
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\runtime\thread_pool\worker.rs:430
  55:     0x7ff64928b31c - tokio::runtime::thread_pool::worker::Context::run
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\runtime\thread_pool\worker.rs:397
  56:     0x7ff64928b1b7 - tokio::runtime::thread_pool::worker::run::closure$0
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\runtime\thread_pool\worker.rs:382
  57:     0x7ff64929f5f6 - tokio::macros::scoped_tls::ScopedKey<tokio::runtime::thread_pool::worker::Context>::set<tokio::runtime::thread_pool::worker::Context,tokio::runtime::thread_pool::worker::run::closure_env$0,tuple$<> >
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\macros\scoped_tls.rs:61
  58:     0x7ff64928b089 - tokio::runtime::thread_pool::worker::run
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\runtime\thread_pool\worker.rs:379
  59:     0x7ff64928af7e - tokio::runtime::thread_pool::worker::impl$0::launch::closure$0
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\runtime\thread_pool\worker.rs:358
  60:     0x7ff649244f7b - tokio::runtime::blocking::task::impl$2::poll<tokio::runtime::thread_pool::worker::impl$0::launch::closure_env$0,tuple$<> >
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\runtime\blocking\task.rs:42
  61:     0x7ff649243960 - tokio::runtime::task::core::impl$3::poll::closure$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::thread_pool::worker::impl$0::launch::closure_env$0> >
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\runtime\task\core.rs:165
  62:     0x7ff649288c72 - tokio::loom::std::unsafe_cell::UnsafeCell<enum$<tokio::runtime::task::core::Stage<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::thread_pool::worker::impl$0::launch::closure_env$0> > > >::with_mut<enum$<tokio::runtime::task::core::Stage<toki
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\loom\std\unsafe_cell.rs:14
  63:     0x7ff64924364f - tokio::runtime::task::core::CoreStage<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::thread_pool::worker::impl$0::launch::closure_env$0> >::poll<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::thread_pool::worker::impl$0::launch
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\runtime\task\core.rs:155
  64:     0x7ff64927f71a - tokio::runtime::task::harness::poll_future::closure$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::thread_pool::worker::impl$0::launch::closure_env$0> >
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\runtime\task\harness.rs:470
  65:     0x7ff64926c973 - core::panic::unwind_safe::impl$23::call_once<enum$<core::task::poll::Poll<tuple$<> > >,tokio::runtime::task::harness::poll_future::closure_env$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::thread_pool::worker::impl$0::launch::closure_env$
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\panic\unwind_safe.rs:271
  66:     0x7ff6492d2cd0 - std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::thread_pool::worker::impl$0::launch::closure_env$0> > >,enum$<co
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\std\src\panicking.rs:492
  67:     0x7ff6492d4853 - std::panicking::panicking
  68:     0x7ff6492d1859 - std::panicking::try<enum$<core::task::poll::Poll<tuple$<> > >,core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::thread_pool::worker::impl$0::la
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\std\src\panicking.rs:456
  69:     0x7ff64927448b - std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::thread_pool::worker::impl$0::launch::closure_env$0> > >,enum$<core::
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\std\src\panic.rs:137
  70:     0x7ff64927f138 - tokio::runtime::task::harness::poll_future<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::thread_pool::worker::impl$0::launch::closure_env$0> >
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\runtime\task\harness.rs:458
  71:     0x7ff64927b005 - tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::thread_pool::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::NoopSchedule>::poll_inner<tokio::runtime::blocking::task::BlockingT
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\runtime\task\harness.rs:104
  72:     0x7ff64927a653 - tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::thread_pool::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::NoopSchedule>::poll<tokio::runtime::blocking::task::BlockingTask<to
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\runtime\task\harness.rs:57
  73:     0x7ff6492a03a2 - tokio::runtime::task::raw::poll<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::thread_pool::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::NoopSchedule>
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\runtime\task\raw.rs:144
  74:     0x7ff6492a0150 - tokio::runtime::task::raw::RawTask::poll
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\runtime\task\raw.rs:84
  75:     0x7ff64923d4e8 - tokio::runtime::task::UnownedTask<tokio::runtime::blocking::schedule::NoopSchedule>::run<tokio::runtime::blocking::schedule::NoopSchedule>
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\runtime\task\mod.rs:413
  76:     0x7ff649295be5 - tokio::runtime::blocking::pool::Task::run
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\runtime\blocking\pool.rs:91
  77:     0x7ff64929809e - tokio::runtime::blocking::pool::Inner::run
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\runtime\blocking\pool.rs:325
  78:     0x7ff649297743 - tokio::runtime::blocking::pool::impl$4::spawn_thread::closure$0
                               at C:\Users\KAJ7\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.18.2\src\runtime\blocking\pool.rs:300
  79:     0x7ff64923f62a - std::sys_common::backtrace::__rust_begin_short_backtrace<tokio::runtime::blocking::pool::impl$4::spawn_thread::closure_env$0,tuple$<> >
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\std\src\sys_common\backtrace.rs:122
  80:     0x7ff6492496a1 - std::thread::impl$0::spawn_unchecked_::closure$1::closure$0<tokio::runtime::blocking::pool::impl$4::spawn_thread::closure_env$0,tuple$<> >
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\std\src\thread\mod.rs:498
  81:     0x7ff64926ca21 - core::panic::unwind_safe::impl$23::call_once<tuple$<>,std::thread::impl$0::spawn_unchecked_::closure$1::closure_env$0<tokio::runtime::blocking::pool::impl$4::spawn_thread::closure_env$0,tuple$<> > >
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\panic\unwind_safe.rs:271
  82:     0x7ff6492d3035 - std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<std::thread::impl$0::spawn_unchecked_::closure$1::closure_env$0<tokio::runtime::blocking::pool::impl$4::spawn_thread::closure_env$0,tuple$<> > >,tuple$<> >
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\std\src\panicking.rs:492
  83:     0x7ff6492d4853 - std::panicking::panicking
  84:     0x7ff6492d0f88 - std::panicking::try<tuple$<>,core::panic::unwind_safe::AssertUnwindSafe<std::thread::impl$0::spawn_unchecked_::closure$1::closure_env$0<tokio::runtime::blocking::pool::impl$4::spawn_thread::closure_env$0,tuple$<> > > >
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\std\src\panicking.rs:456
  85:     0x7ff649274391 - std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<std::thread::impl$0::spawn_unchecked_::closure$1::closure_env$0<tokio::runtime::blocking::pool::impl$4::spawn_thread::closure_env$0,tuple$<> > >,tuple$<> >
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\std\src\panic.rs:137
  86:     0x7ff649249493 - std::thread::impl$0::spawn_unchecked_::closure$1<tokio::runtime::blocking::pool::impl$4::spawn_thread::closure_env$0,tuple$<> >
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\std\src\thread\mod.rs:497
  87:     0x7ff6492520ae - core::ops::function::FnOnce::call_once<std::thread::impl$0::spawn_unchecked_::closure_env$1<tokio::runtime::blocking::pool::impl$4::spawn_thread::closure_env$0,tuple$<> >,tuple$<> >    
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\ops\function.rs:227
  88:     0x7ff649356cfc - alloc::boxed::impl$44::call_once
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\alloc\src\boxed.rs:1861
  89:     0x7ff649356cfc - alloc::boxed::impl$44::call_once
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\alloc\src\boxed.rs:1861
  90:     0x7ff649356cfc - std::sys::windows::thread::impl$0::new::thread_start
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys\windows\thread.rs:57
  91:     0x7ff9787754e0 - BaseThreadInitThunk
  92:     0x7ff97a52485b - RtlUserThreadStart
```

**Comment by KAJdev** [comment]
Fixed this with more fiddling around with my ENV and providing the necessary DLLs. I'll write a doc for compiling on windows soon.
