### ISSUE TITLE
[ENG-1861] Spacedrop failing to transfer on Fedora Linux

### ISSUE THREAD

**Issue by greendoescode** [spacedriveapp/spacedrive#2677]
### Check for other issues

- [X] I've checked for other issues, and none exist.

### Issue description

When I run spacedrive using pnpm tauri dev or through sandboxed flatpak, spacedrop fails to run. This also applies to official builds.

### Steps to reproduce

1. Run spacedrive
2. try to connect to another spacedrive instance running on Linux/fedora
3. the instance being connected to crashes

### Platform and versions

- OS: Fedora 40
- Spacedrive: 0.4.2, but doesn't work in dev either.

<details><summary> Development tool versions (optional) </summary><pre>

</pre></details>

### Stack trace

```shell
2024-08-14T19:56:16.227183Z ERROR sd_core: panicked at /home/runner/work/spacedrive/spacedrive/core/src/p2p/operations/ping.rs:36:10:
Failed to send pong: Custom { kind: ConnectionReset, error: Stopped(0) }, panic.file: "/home/runner/work/spacedrive/spacedrive/core/src/p2p/operations/ping.rs:36", panic.column: 10
    at core/src/lib.rs:292

fatal runtime error: failed to initiate panic, error 3
```
```


### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow the Code of Conduct.

**Comment by iLynxcat** [comment]
for clarification, this only works if you're running the app either in development or through the Flatpak distribution you're working on?

**Comment by greendoescode** [comment]
> for clarification, this only works if you're running the app either in development or through the Flatpak distribution you're working on?

I wasn't able to get spacedrop to work in any instance, I tried `pnpm run dev`, flatpak and the official 0.4.2

**Comment by HeavenVolkoff** [comment]
Very likely the same issue as #2561

Tbh the p2p code is very brittle atm. We are currently working on our official cloud support (spacedrive cloud, not external providers) and next we are going to rework p2p so it can leverage some of the new architecture we built for cloud using [n0-computer/iroh](https://github.com/n0-computer/iroh), which should solve the majority of the current p2p implementation has.

**Comment by jamiepine** [comment]
Closing due to v2 rewrite. If you encounter this issue in v2, please open a new issue.
