### ISSUE TITLE
webp dimension issue of some kind causing crash on start

### ISSUE THREAD

**Issue by kaithar** [spacedriveapp/spacedrive#2736]
### Check for other issues

- [X] I've checked for other issues, and none exist.

### Issue description

When trying to start spacedrive after giving it some files to look at, it panics immediately using the webp crate ... not really sure what's going on beyond that.

### Platform and versions

- OS: Gentoo
- Spacedrive: latest alpha ... 0.4.2 or something?

### Stack trace

```shell
2024-09-27T00:05:52.703833Z ERROR sd_core: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/webp-0.2.6/src/encoder.rs:70:44:
called `Result::unwrap()` on an `Err` value: VP8_ENC_ERROR_BAD_DIMENSION, panic.file: "/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/webp-0.2.6/src/encoder.rs:70", panic.column: 44
at core/src/lib.rs:290
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct.

**Comment by HeavenVolkoff** [comment]
Hey @kaithar,

Thanks for reporting this issue! Could you provide more details about the types of files you were viewing? Were they images? If so, could you share them here? The webp error is likely originating from our thumbnail logic, which heavily relies on the webp crate.

**Comment by matheus-consoli** [comment]
the crash comes from the dep we're using (or rather on how we're using it)
it's trying to generate a thumbnail for a file with picture "invalid width/height" (see [libwebp VP8_ENC_ERROR_BAD_DIMENSION](https://github.com/webmproject/libwebp/blob/220ee52967c121adf3c690fbd0605a7de6371943/src/webp/encode.h#L286))
we shouldn't crash on such a case, but keep processing the remaining files and count that one as a non-critical error

I have a fix on the way, thanks for reporting!

**Comment by kaithar** [comment]
Thanks for the fix :+1: 

@HeavenVolkoff funnily enough, since there's nothing I could see that indicated what file it was processing at the time, I don't know what file up set it, just that it was a webp somewhere in the large selection of files I gave it.
