### ISSUE TITLE
[BUG] Install Error - Linux

### ISSUE THREAD

**Issue by abhnva** [spacedriveapp/spacedrive#42]
**Describe the bug**
Install error on Linux (Pop!_OS)

**Error**
```spacedrive on  main via  v18.0.0 via 🦀 v1.60.0 
❯ pnpm i
Scope: all 11 workspace projects
packages/interface                       |  WARN  deprecated @types/pretty-bytes@5.2.0
packages/ui                              |  WARN  deprecated uuid@3.3.2
packages/ui                              |  WARN  deprecated uuid@3.3.2
apps/desktop                             |  WARN  deprecated svgo@1.3.2
packages/ui                              |  WARN  deprecated core-js@2.6.12
Packages: +842
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/astro/.local/share/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 870, reused 829, downloaded 3, added 842, done

devDependencies:
+ prettier 2.6.2
+ turbo 1.2.4

 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

apps/desktop
└─┬ vite-plugin-react-svg
  └─┬ @babel/plugin-transform-react-jsx
    ├── ✕ missing peer @babel/core@^7.0.0-0
    └─┬ @babel/plugin-syntax-jsx
      └── ✕ missing peer @babel/core@^7.0.0-0
Peer dependencies that should be installed:
  @babel/core@">=7.0.0-0 <8.0.0"  

apps/landing
├─┬ @babel/preset-react
│ ├── ✕ missing peer @babel/core@^7.0.0-0
│ ├─┬ @babel/plugin-transform-react-display-name
│ │ └── ✕ missing peer @babel/core@^7.0.0-0
│ ├─┬ @babel/plugin-transform-react-jsx
│ │ ├── ✕ missing peer @babel/core@^7.0.0-0
│ │ └─┬ @babel/plugin-syntax-jsx
│ │   └── ✕ missing peer @babel/core@^7.0.0-0
│ ├─┬ @babel/plugin-transform-react-jsx-development
│ │ └── ✕ missing peer @babel/core@^7.0.0-0
│ └─┬ @babel/plugin-transform-react-pure-annotations
│   └── ✕ missing peer @babel/core@^7.0.0-0
├─┬ ts-node
│ └── ✕ missing peer @types/node@"*"
├─┬ @tailwindcss/typography
│ └── ✕ missing peer tailwindcss@">=3.0.0 || >= 3.0.0-alpha.1 || insiders"
├─┬ @icons-pack/react-simple-icons
│ └── ✕ unmet peer react@"^16.13 || ^17": found 18.0.0
└─┬ react-helmet
  └─┬ react-side-effect
    └── ✕ unmet peer react@"^16.3.0 || ^17.0.0": found 18.0.0
Peer dependencies that should be installed:
  @babel/core@">=7.0.0-0 <8.0.0"                         tailwindcss@">=3.0.0 || >= 3.0.0-alpha.1 || insiders"  
  @types/node@"*"                                        

packages/client
└─┬ react-query
  └── ✕ unmet peer react@"^16.8.0 || ^17.0.0": found 18.0.0

packages/interface
├─┬ @apollo/client
│ ├── ✕ missing peer graphql@"^14.0.0 || ^15.0.0 || ^16.0.0"
│ ├── ✕ unmet peer react@"^16.8.0 || ^17.0.0": found 18.0.0
│ ├─┬ @graphql-typed-document-node/core
│ │ └── ✕ missing peer graphql@"^0.8.0 || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0 || ^16.0.0"
│ └─┬ graphql-tag
│   └── ✕ missing peer graphql@"^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0 || ^16.0.0"
├─┬ autoprefixer
│ └── ✕ missing peer postcss@^8.1.0
├─┬ @radix-ui/react-dialog
│ ├── ✕ unmet peer react@"^16.8 || ^17.0": found 18.0.0
│ ├── ✕ unmet peer react-dom@"^16.8 || ^17.0": found 18.0.0
│ ├─┬ @radix-ui/react-compose-refs
│ │ └── ✕ unmet peer react@"^16.8 || ^17.0": found 18.0.0
│ ├─┬ @radix-ui/react-context
│ │ └── ✕ unmet peer react@"^16.8 || ^17.0": found 18.0.0
│ ├─┬ @radix-ui/react-dismissable-layer
│ │ ├── ✕ unmet peer react@"^16.8 || ^17.0": found 18.0.0
│ │ ├─┬ @radix-ui/react-primitive
│ │ │ ├── ✕ unmet peer react@"^16.8 || ^17.0": found 18.0.0
│ │ │ └─┬ @radix-ui/react-slot
│ │ │   └── ✕ unmet peer react@"^16.8 || ^17.0": found 18.0.0
│ │ ├─┬ @radix-ui/react-use-body-pointer-events
│ │ │ ├── ✕ unmet peer react@"^16.8 || ^17.0": found 18.0.0
│ │ │ └─┬ @radix-ui/react-use-layout-effect
│ │ │   └── ✕ unmet peer react@"^16.8 || ^17.0": found 18.0.0
│ │ ├─┬ @radix-ui/react-use-callback-ref
│ │ │ └── ✕ unmet peer react@"^16.8 || ^17.0": found 18.0.0
│ │ └─┬ @radix-ui/react-use-escape-keydown
│ │   └── ✕ unmet peer react@"^16.8 || ^17.0": found 18.0.0
│ ├─┬ @radix-ui/react-focus-guards
│ │ └── ✕ unmet peer react@"^16.8 || ^17.0": found 18.0.0
│ ├─┬ @radix-ui/react-focus-scope
│ │ └── ✕ unmet peer react@"^16.8 || ^17.0": found 18.0.0
│ ├─┬ @radix-ui/react-id
│ │ └── ✕ unmet peer react@"^16.8 || ^17.0": found 18.0.0
│ ├─┬ @radix-ui/react-portal
│ │ ├── ✕ unmet peer react@"^16.8 || ^17.0": found 18.0.0
│ │ └── ✕ unmet peer react-dom@"^16.8 || ^17.0": found 18.0.0
│ ├─┬ @radix-ui/react-use-controllable-state
│ │ └── ✕ unmet peer react@"^16.8 || ^17.0": found 18.0.0
│ └─┬ react-remove-scroll
│   ├─┬ react-remove-scroll-bar
│   │ ├── ✕ unmet peer react@"^16.8.0 || ^17.0.0": found 18.0.0
│   │ ├── ✕ unmet peer @types/react@"^16.8.0 || ^17.0.0": found 18.0.0
│   │ └─┬ react-style-singleton
│   │   ├── ✕ unmet peer react@"^16.8.0 || ^17.0.0": found 18.0.0
│   │   └── ✕ unmet peer @types/react@"^16.8.0 || ^17.0.0": found 18.0.0
│   ├─┬ use-callback-ref
│   │ ├── ✕ unmet peer react@"^16.8.0 || ^17.0.0": found 18.0.0
│   │ └── ✕ unmet peer @types/react@"^16.8.0 || ^17.0.0": found 18.0.0
│   └─┬ use-sidecar
│     └── ✕ unmet peer react@"^16.8.0 || ^17.0.0": found 18.0.0
├─┬ @radix-ui/react-dropdown-menu
│ ├── ✕ unmet peer react@"^16.8 || ^17.0": found 18.0.0
│ ├── ✕ unmet peer react-dom@"^16.8 || ^17.0": found 18.0.0
│ └─┬ @radix-ui/react-menu
│   ├── ✕ unmet peer react@"^16.8 || ^17.0": found 18.0.0
│   ├── ✕ unmet peer react-dom@"^16.8 || ^17.0": found 18.0.0
│   ├─┬ @radix-ui/react-collection
│   │ └── ✕ unmet peer react@"^16.8 || ^17.0": found 18.0.0
│   ├─┬ @radix-ui/react-popper
│   │ ├── ✕ unmet peer react@"^16.8 || ^17.0": found 18.0.0
│   │ ├─┬ @radix-ui/react-arrow
│   │ │ └── ✕ unmet peer react@"^16.8 || ^17.0": found 18.0.0
│   │ ├─┬ @radix-ui/react-use-rect
│   │ │ └── ✕ unmet peer react@"^16.8 || ^17.0": found 18.0.0
│   │ └─┬ @radix-ui/react-use-size
│   │   └── ✕ unmet peer react@"^16.8 || ^17.0": found 18.0.0
│   ├─┬ @radix-ui/react-roving-focus
│   │ └── ✕ unmet peer react@"^16.8 || ^17.0": found 18.0.0
│   └─┬ @radix-ui/react-use-direction
│     └── ✕ unmet peer react@"^16.8 || ^17.0": found 18.0.0
├─┬ @radix-ui/react-icons
│ └── ✕ unmet peer react@"^16.x || ^17.x": found 18.0.0
├─┬ @radix-ui/react-progress
│ └── ✕ unmet peer react@"^16.8 || ^17.0": found 18.0.0
├─┬ @radix-ui/react-slider
│ ├── ✕ unmet peer react@"^16.8 || ^17.0": found 18.0.0
│ └─┬ @radix-ui/react-use-previous
│   └── ✕ unmet peer react@"^16.8 || ^17.0": found 18.0.0
├─┬ react-json-view
│ ├── ✕ unmet peer react@"^17.0.0 || ^16.3.0 || ^15.5.4": found 18.0.0
│ ├── ✕ unmet peer react-dom@"^17.0.0 || ^16.3.0 || ^15.5.4": found 18.0.0
│ ├─┬ flux
│ │ └── ✕ unmet peer react@"^15.0.2 || ^16.0.0 || ^17.0.0": found 18.0.0
│ └─┬ react-textarea-autosize
│   ├── ✕ unmet peer react@"^16.8.0 || ^17.0.0": found 18.0.0
│   ├─┬ use-composed-ref
│   │ └── ✕ unmet peer react@"^16.8.0 || ^17.0.0": found 18.0.0
│   └─┬ use-latest
│     └── ✕ unmet peer react@"^16.8.0 || ^17.0.0": found 18.0.0
├─┬ react-query
│ └── ✕ unmet peer react@"^16.8.0 || ^17.0.0": found 18.0.0
└─┬ react-spline
  └── ✕ unmet peer react@^16.0.0: found 18.0.0
Peer dependencies that should be installed:
  graphql@">=14.0.0 <15.0.0 || >=15.0.0 <16.0.0 || >=16.0.0 <17.0.0"  postcss@^8.1.0                                                      

packages/ui
└─┬ @headlessui/react
  └── ✕ missing peer react-dom@"^16 || ^17 || ^18"
Peer dependencies that should be installed:
  react-dom@"^16 || ^17 || ^18"  
[WARN] - (starship::utils): Executing command "/usr/bin/git" timed out.
```

**Comment by abhnva** [comment]
This is 4th time I'm compiling this.

**Comment by abhnva** [comment]
pnpm prep -
```spacedrive on  main via  v18.0.0 via 🦀 v1.60.0 
❯ pnpm prep

> spacedrive@0.0.0 prep /home/astro/Downloads/spacedrive
> pnpm db:gen && pnpm core codegen


> spacedrive@0.0.0 db:gen /home/astro/Downloads/spacedrive
> pnpm core prisma generate


> spacedrive@0.0.0 core /home/astro/Downloads/spacedrive
> pnpm --filter @sd/core --  "prisma" "generate"


> @sd/core@0.0.0 prisma /home/astro/Downloads/spacedrive/core
> cargo prisma "generate"

  Downloaded pbkdf2 v0.10.1
  Downloaded filetime v0.2.16
  Downloaded serde_with v1.13.0
  Downloaded toml v0.5.9
  Downloaded tracing v0.1.34
  Downloaded weezl v0.1.6
  Downloaded tracing-log v0.1.3
  Downloaded exr v1.4.2
  Downloaded enumflags2 v0.7.5
  Downloaded bson v2.2.0
  Downloaded spin v0.9.3
  Downloaded rustc_version_runtime v0.2.1
  Downloaded fs_extra v1.2.0
  Downloaded backtrace v0.3.65
  Downloaded rustls-pemfile v0.3.0
  Downloaded object v0.28.3
  Downloaded rayon-core v1.9.2
  Downloaded rayon v1.5.2
  Downloaded tracing-core v0.1.26
  Downloaded typed-builder v0.10.0
  Downloaded tracing-subscriber v0.3.11
  Downloaded sysinfo v0.23.10
  Downloaded mongodb v2.2.1
  Downloaded tiff v0.7.2
  Downloaded libc v0.2.124
  Downloaded tokio-rustls v0.23.3
  Downloaded ipnet v2.5.0
  Downloaded httparse v1.7.0
  Downloaded anyhow v1.0.57
  Downloaded 29 crates (4.1 MB) in 11.98s (largest was `tiff` at 1.4 MB)
   Compiling libc v0.2.124
   Compiling proc-macro2 v1.0.37
   Compiling unicode-xid v0.2.2
   Compiling cfg-if v1.0.0
   Compiling syn v1.0.91
   Compiling autocfg v1.1.0
   Compiling pkg-config v0.3.25
   Compiling log v0.4.16
   Compiling memchr v2.4.1
   Compiling serde_derive v1.0.136
   Compiling once_cell v1.10.0
   Compiling pin-project-lite v0.2.8
   Compiling version_check v0.9.4
   Compiling serde v1.0.136
   Compiling futures-core v0.3.21
   Compiling bytes v1.1.0
   Compiling itoa v1.0.1
   Compiling futures-task v0.3.21
   Compiling futures-sink v0.3.21
   Compiling lazy_static v1.4.0
   Compiling futures-channel v0.3.21
   Compiling foreign-types-shared v0.1.1
   Compiling fnv v1.0.7
   Compiling openssl v0.10.38
   Compiling futures-util v0.3.21
   Compiling slab v0.4.6
   Compiling futures-io v0.3.21
   Compiling bitflags v1.3.2
   Compiling httparse v1.7.0
   Compiling pin-utils v0.1.0
   Compiling tinyvec_macros v0.1.0
   Compiling native-tls v0.2.10
   Compiling matches v0.1.9
   Compiling openssl-probe v0.1.5
   Compiling percent-encoding v2.1.0
   Compiling try-lock v0.2.3
   Compiling tower-service v0.3.1
   Compiling ryu v1.0.9
   Compiling crc32fast v1.3.2
   Compiling httpdate v1.0.2
   Compiling unicode-bidi v0.3.7
   Compiling encoding_rs v0.8.31
   Compiling serde_json v1.0.79
   Compiling adler v1.0.2
   Compiling mime v0.3.16
   Compiling base64 v0.13.0
   Compiling ipnet v2.5.0
   Compiling regex-syntax v0.6.25
   Compiling convert_case v0.5.0
   Compiling indexmap v1.8.1
   Compiling ahash v0.7.6
   Compiling tracing-core v0.1.26
   Compiling foreign-types v0.3.2
   Compiling http v0.2.6
   Compiling tinyvec v1.5.1
   Compiling form_urlencoded v1.0.1
   Compiling miniz_oxide v0.5.1
   Compiling unicode-normalization v0.1.19
   Compiling http-body v0.4.4
   Compiling jobserver v0.1.24
   Compiling getrandom v0.2.6
   Compiling num_cpus v1.13.1
   Compiling socket2 v0.4.4
   Compiling dirs-sys v0.3.7
   Compiling quote v1.0.18
   Compiling mio v0.8.2
   Compiling want v0.3.0
   Compiling aho-corasick v0.7.18
   Compiling idna v0.2.3
   Compiling cc v1.0.73
   Compiling directories v4.0.1
   Compiling url v2.2.2
   Compiling regex v1.5.5
   Compiling hashbrown v0.11.2
   Compiling openssl-sys v0.9.72
   Compiling libz-sys v1.1.5
   Compiling tokio-macros v1.7.0
   Compiling tracing-attributes v0.1.20
   Compiling futures-macro v0.3.21
   Compiling tokio v1.17.0
   Compiling tracing v0.1.34
   Compiling serde_urlencoded v0.7.1
   Compiling serde_path_to_error v0.1.7
   Compiling flate2 v1.0.23
   Compiling tokio-util v0.7.1
   Compiling h2 v0.3.13
   Compiling tokio-native-tls v0.3.0
   Compiling hyper v0.14.18
   Compiling hyper-tls v0.5.0
   Compiling reqwest v0.11.10
   Compiling prisma-client-rust-cli v0.4.0 (https://github.com/Brendonovich/prisma-client-rust.git?tag=0.4.0#4c6c4bf9)
   Compiling prisma-cli v0.1.0 (/home/astro/Downloads/spacedrive/core/prisma)
    Finished dev [unoptimized + debuginfo] target(s) in 8m 01s
     Running `/home/astro/Downloads/spacedrive/target/debug/prisma-cli generate`
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client Rust to ./src/prisma.rs in 4.15s


> spacedrive@0.0.0 core /home/astro/Downloads/spacedrive
> pnpm --filter @sd/core --  "codegen"


> @sd/core@0.0.0 codegen /home/astro/Downloads/spacedrive/core
> cargo test && ts-node ./scripts/bindingsIndex.ts

   Compiling scopeguard v1.1.0
   Compiling typenum v1.15.0
   Compiling ppv-lite86 v0.2.16
   Compiling crossbeam-utils v0.8.8
   Compiling smallvec v1.8.0
   Compiling glob v0.3.0
   Compiling subtle v2.4.1
   Compiling lazycell v1.3.0
   Compiling minimal-lexical v0.2.1
   Compiling async-trait v0.1.53
   Compiling bindgen v0.59.2
   Compiling byteorder v1.4.3
   Compiling cpufeatures v0.2.2
   Compiling peeking_take_while v0.1.2
   Compiling static_assertions v1.1.0
   Compiling shlex v1.1.0
   Compiling rustc-hash v1.1.0
   Compiling cfg-if v0.1.10
   Compiling either v1.6.1
   Compiling parking_lot_core v0.9.2
   Compiling proc-macro-hack v0.5.19
   Compiling encoding_index_tests v0.1.4
   Compiling frunk_core v0.4.0
   Compiling ucd-trie v0.1.3
   Compiling fallible-iterator v0.2.0
   Compiling radium v0.6.2
   Compiling hex v0.4.3
   Compiling crossbeam-queue v0.3.5
   Compiling linked-hash-map v0.5.4
   Compiling tap v1.0.1
   Compiling rust_decimal v1.23.1
   Compiling maplit v1.0.2
   Compiling siphasher v0.3.10
   Compiling getrandom v0.1.16
   Compiling bit-vec v0.6.3
   Compiling funty v1.2.0
   Compiling arrayvec v0.7.2
   Compiling num_threads v0.1.5
   Compiling metrics v0.12.1
   Compiling saturating v0.1.0
   Compiling pretty-hex v0.1.1
   Compiling metrics-core v0.5.2
   Compiling fallible-streaming-iterator v0.1.9
   Compiling semver-parser v0.7.0
   Compiling futures-timer v3.0.2
   Compiling connection-string v0.1.14
   Compiling untrusted v0.7.1
   Compiling base64 v0.12.3
   Compiling spin v0.5.2
   Compiling unindent v0.1.8
   Compiling ident_case v1.0.1
   Compiling strsim v0.10.0
   Compiling match_cfg v0.1.0
   Compiling rustversion v1.0.6
   Compiling rayon-core v1.9.2
   Compiling gimli v0.26.1
   Compiling rustls v0.20.4
   Compiling heck v0.4.0
   Compiling quick-error v1.2.3
   Compiling data-encoding v2.3.2
   Compiling rustc-demangle v0.1.21
   Compiling anyhow v1.0.57
   Compiling maybe-uninit v2.0.0
   Compiling take_mut v0.2.2
   Compiling adler32 v1.2.0
   Compiling void v1.0.2
   Compiling weezl v0.1.6
   Compiling fixedbitset v0.1.9
   Compiling ordermap v0.3.5
   Compiling ascii v0.9.3
   Compiling unicode-segmentation v1.9.0
   Compiling half v1.8.2
   Compiling color_quant v1.1.0
   Compiling same-file v1.0.6
   Compiling lebe v0.5.1
   Compiling bit_field v0.10.1
   Compiling Inflector v0.11.4
   Compiling bytemuck v1.9.1
   Compiling ffmpeg-next v5.0.3
   Compiling termcolor v1.1.3
   Compiling sysinfo v0.23.10
   Compiling scoped_threadpool v0.1.9
   Compiling humantime v2.1.0
   Compiling fs_extra v1.2.0
   Compiling libloading v0.7.3
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling indexmap v1.8.1
   Compiling lock_api v0.4.7
   Compiling memoffset v0.6.5
   Compiling crossbeam-epoch v0.9.8
   Compiling num-bigint v0.4.3
   Compiling num-bigint v0.3.3
   Compiling rayon v1.5.2
   Compiling crossbeam-utils v0.7.2
   Compiling num-rational v0.4.0
   Compiling num-iter v0.1.42
   Compiling sharded-slab v0.1.4
   Compiling thread_local v1.1.4
   Compiling generic-array v0.14.5
   Compiling lock_api v0.3.4
   Compiling clang-sys v1.3.1
   Compiling pem v1.0.2
   Compiling rustls-pemfile v0.3.0
   Compiling lexical-util v0.8.3
   Compiling itertools v0.10.3
   Compiling encoding-index-tradchinese v1.20141219.5
   Compiling encoding-index-singlebyte v1.20141219.5
   Compiling encoding-index-korean v1.20141219.5
   Compiling encoding-index-simpchinese v1.20141219.5
   Compiling encoding-index-japanese v1.20141219.5
   Compiling pest v2.1.3
   Compiling lru-cache v0.1.2
   Compiling wyz v0.4.0
   Compiling phf_shared v0.10.0
   Compiling semver v0.9.0
   Compiling indoc v1.0.4
   Compiling addr2line v0.17.0
   Compiling unreachable v1.0.0
   Compiling deflate v1.0.0
   Compiling inflate v0.4.5
   Compiling petgraph v0.4.13
   Compiling gif v0.11.3
   Compiling walkdir v2.3.2
   Compiling tracing-subscriber v0.3.11
   Compiling lexical-write-integer v0.8.3
   Compiling lexical-parse-integer v0.8.3
   Compiling encoding v0.2.33
   Compiling phf v0.10.1
   Compiling pest_meta v2.1.3
   Compiling rustc_version v0.2.3
   Compiling time v0.1.44
   Compiling subprocess v0.2.8
   Compiling atty v0.2.14
   Compiling time v0.3.9
   Compiling parking_lot_core v0.7.2
   Compiling hostname v0.1.5
   Compiling hostname v0.3.1
   Compiling net2 v0.2.37
   Compiling iovec v0.1.4
   Compiling inotify-sys v0.1.5
   Compiling filetime v0.2.16
   Compiling nom v7.1.1
   Compiling object v0.28.3
   Compiling combine v3.8.1
   Compiling os_info v3.2.0
   Compiling tracing-log v0.1.3
   Compiling stringprep v0.1.2
   Compiling crossbeam-channel v0.5.4
   Compiling png v0.17.5
   Compiling sized-chunks v0.3.1
   Compiling lexical-parse-float v0.8.3
   Compiling lexical-write-float v0.8.4
   Compiling bitvec v0.22.3
   Compiling rustc_version_runtime v0.2.1
   Compiling im v13.0.0
   Compiling rand_core v0.6.3
   Compiling nanorand v0.7.0
   Compiling threadpool v1.8.1
   Compiling colored v2.0.0
   Compiling rand_core v0.5.1
   Compiling parking_lot v0.10.2
   Compiling resolv-conf v0.7.0
   Compiling mio v0.6.23
   Compiling inotify v0.7.1
   Compiling include_dir_macros v0.7.2
   Compiling parking_lot v0.12.0
   Compiling spin v0.9.3
   Compiling crossbeam-queue v0.2.3
   Compiling cexpr v0.6.0
   Compiling block-buffer v0.10.2
   Compiling crypto-common v0.1.3
   Compiling lexical-core v0.8.3
   Compiling cmake v0.1.48
   Compiling libsqlite3-sys v0.22.2
   Compiling ring v0.16.20
   Compiling backtrace v0.3.65
   Compiling libwebp-sys v0.4.2
   Compiling ring v0.17.0-alpha.11
   Compiling rand_chacha v0.3.1
   Compiling rand_chacha v0.2.2
   Compiling mio-extras v2.0.6
   Compiling thiserror-impl v1.0.30
   Compiling pin-project-internal v1.0.10
   Compiling frunk_proc_macro_helpers v0.1.0
   Compiling enumflags2_derive v0.7.4
   Compiling pest_generator v2.1.3
   Compiling darling_core v0.13.4
   Compiling enum-as-inner v0.4.0
   Compiling user-facing-error-macros v0.1.0 (https://github.com/Brendonovich/prisma-engines?rev=8b94a80a2d8f12a2916fe28e3218162aa71e8539#8b94a80a)
   Compiling typed-builder v0.10.0
   Compiling derivative v2.2.0
   Compiling ts-rs-macros v6.1.2
   Compiling core-derive v0.1.0 (/home/astro/Downloads/spacedrive/core/derive)
   Compiling include_dir v0.7.2
   Compiling crossbeam-deque v0.8.1
   Compiling prisma-inflector v0.1.0 (https://github.com/Brendonovich/prisma-engines?rev=8b94a80a2d8f12a2916fe28e3218162aa71e8539#8b94a80a)
   Compiling digest v0.10.3
   Compiling lexical v6.1.0
   Compiling lru v0.7.5
   Compiling hashlink v0.7.0
   Compiling rand v0.8.5
   Compiling rand v0.7.3
   Compiling notify v4.0.17
   Compiling thiserror v1.0.30
   Compiling frunk_proc_macros_impl v0.1.0
   Compiling frunk_derives v0.4.0
   Compiling pin-project v1.0.10
   Compiling enumflags2 v0.7.5
   Compiling pest_derive v2.1.0
   Compiling darling_macro v0.13.4
   Compiling crossbeam v0.8.1
   Compiling bigdecimal v0.3.0
   Compiling bigdecimal v0.2.2
   Compiling sha2 v0.10.2
   Compiling hmac v0.12.1
   Compiling md-5 v0.10.1
   Compiling sha-1 v0.10.0
   Compiling pbkdf2 v0.10.1
   Compiling mysql_common v0.28.2
   Compiling ffmpeg-sys-next v5.0.1
   Compiling twox-hash v1.6.2
   Compiling uuid v0.8.2
   Compiling chrono v0.4.19
   Compiling serde_bytes v0.11.5
   Compiling toml v0.5.9
   Compiling cuid v0.1.0 (https://github.com/prisma/cuid-rust?rev=4ffb2e47c772af62fed3ddc92bb7fc444d19e159#4ffb2e47)
   Compiling hotwatch v0.4.6
   Compiling futures-executor v0.3.21
   Compiling asynchronous-codec v0.5.0
   Compiling tokio-util v0.6.9
   Compiling diagnostics v0.1.0 (https://github.com/Brendonovich/prisma-engines?rev=8b94a80a2d8f12a2916fe28e3218162aa71e8539#8b94a80a)
   Compiling mobc v0.7.3 (https://github.com/prisma/mobc?tag=1.0.0#75c68f10)
   Compiling trust-dns-proto v0.21.2
   Compiling ts-rs v6.1.2
   Compiling frunk_proc_macros v0.1.0
   Compiling tracing-futures v0.2.5
   Compiling flume v0.10.12
   Compiling darling v0.13.4
   Compiling postgres-protocol v0.6.4 (https://github.com/pimeys/rust-postgres?branch=pgbouncer-mode#5ec2a4fa)
error: failed to run custom build command for `ffmpeg-sys-next v5.0.1`

Caused by:
  process didn't exit successfully: `/home/astro/Downloads/spacedrive/target/debug/build/ffmpeg-sys-next-53317404f66992fa/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=LIBAVUTIL_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: `"pkg-config" "--libs" "--cflags" "libavutil"` did not exit successfully: exit status: 1
  error: could not find system library 'libavutil' required by the 'ffmpeg-sys-next' crate

  --- stderr
  Package libavutil was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libavutil.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libavutil' found
  ', /home/astro/.cargo/registry/src/github.com-1ecc6299db9ec823/ffmpeg-sys-next-5.0.1/build.rs:711:14
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
/home/astro/Downloads/spacedrive/core:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @sd/core@0.0.0 codegen: `cargo test && ts-node ./scripts/bindingsIndex.ts`
Exit status 101
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
[WARN] - (starship::utils): Executing command "/usr/local/lib/nodejs/node-v18.0.0-linux-x64/bin/node" timed out.
```

**Comment by oscartbeaumont** [comment]
Refer to #25

**Comment by RockBacon9922** [comment]
@oscartbeaumont When I run pnpm prep after following the other commands in contributing.md I keep getting this error.

> @sd/core@0.0.0 prisma /workspaces/spacedrive/core
> cargo prisma "generate"

    Finished dev [unoptimized + debuginfo] target(s) in 3.72s
     Running `/workspaces/spacedrive/target/debug/prisma-cli generate`
Prisma schema loaded from prisma/schema.prisma
Error: 
     Running `/workspaces/spacedrive/target/debug/prisma-cli`
{"jsonrpc":"2.0","id":1,"result":{"manifest":{"prettyName":"Prisma Client Rust","defaultOutput":"prisma.rs","denylist":null,"requiresGenerators":null,"requiresEngines":null}}}
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/codespace/.cargo/git/checkouts/prisma-client-rust-fa967aa5ad0ec391/31a864a/cli/src/generator/mod.rs:398:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by oscartbeaumont** [comment]
That's look like an error for @Brendonovich

**Comment by luiscassih** [comment]
Hi there, I had the same error, so looking at generator/mod.rs:398:10, it seems that runs Command::new("rustfmt"), and to run that you need to have rust installed using rustup.
So, uninstalling rust and installing rustup solved the issue and pnpm prep runs fine.
Hope it works for you too!
